[[project]]
name = "OPRF-ID"
desc = "vOPRF based Web3 ID system for Web2 identities ported by zkEmail/TLS"
links = [
  { name = "GitHub", url = "https://github.com/curryrasul/oprf-id" },
]

[[project]]
name = "gossip"
desc = "Bot for anon posting in the group chats / Telegram, Discord, etc. powered by zk"
links = [
  { name = "GitHub", url = "https://github.com/curryrasul/gossip" },
]

[[project]]
name = "Circom-MPC"
desc = "Set of tools (compiler/frontend and MP-SPDZ backend) for MPC development in Circom."
links = [
  { name = "GitHub", url = "https://github.com/namnc/circom-2-arithc" },
  { name = "Docs", url = "https://hackmd.io/@curryrasul/S1MtS6skJg" },
]

[[project]]
name = "zkEVM Community Edition"
desc = "PSE's Type-1 zkEVM"
links = [
  { name = "GitHub", url = "https://github.com/privacy-scaling-explorations/zkevm-circuits" },
  { name = "Docs", url = "https://privacy-scaling-explorations.github.io/zkevm-circuits/zkevm_circuits/" },
]

[[project]]
name = "zkEmail & Email Wallet"
desc = "Non-custodial crypto wallet, which is managed through email. Powered with ZK-Email."
links = [
  { name = "GitHub", url = "https://github.com/zkemail/email-wallet/" },
  { name = "Docs", url = "https://docs.prove.email/email-wallet/" },
  { name = "App", url = "https://emailwallet.org/" },
]

[[project]]
name = "Vortex"
desc = "Nouns DAO anonymous voting ⌐◨-◨. Winner of Nouns [Private voting research sprint](https://prop.house/nouns/private-voting-research-sprint)."
links = [
  { name = "GitHub", url = "https://github.com/mizu-dao/vortex" },
  { name = "Docs", url = "https://mizu-dao.github.io/vortex/" },
]

[[project]]
name = "RLN"
desc = "Rate-Limiting Nullifier (or RLN) is a zero-knowledge gadget that enables spam prevention in anonymous environments."
links = [
  { name = "GitHub", url = "https://github.com/Rate-Limiting-Nullifier" },
  { name = "Docs", url = "https://rate-limiting-nullifier.github.io/rln-docs/" },
]

[[project]]
name = "pmtree"
desc = "Persistent, sparse and generic Merkle tree in Rust. Inspired by [monotree](https://github.com/thyeem/monotree)."
links = [
  { name = "GitHub", url = "https://github.com/Rate-Limiting-Nullifier/pmtree" },
  { name = "Crates.io", url = "https://crates.io/crates/pmtree" },
]

[[project]]
name = "VoAn"
desc = "ANonymous VOting platform on NEAR Protocol."
links = [
  { name = "GitHub", url = "https://github.com/curryrasul/voan" },
  { name = "Docs", url = "https://curryrasul.github.io/voan" },
  { name = "App", url = "https://voan.site" },
]