[[project]]
name = "RLN"
desc = "Rate-Limiting Nullifier (or RLN) is a zero-knowledge gadget that enables spam prevention in anonymous environments."
links = [
  { name = "GitHub", url = "https://github.com/Rate-Limiting-Nullifier" },
  { name = "Docs", url = "https://rate-limiting-nullifier.github.io/rln-docs/" },
]

[[project]]
name = "Email Wallet"
desc = "Non-custodial crypto wallet, which is managed through email. Powered with ZK-Email."
links = [
  { name = "GitHub", url = "https://github.com/zkemail/email-wallet/" },
  { name = "Docs", url = "http://docs.sendeth.org/" },
  { name = "App", url = "https://sendeth.org/" },
]

[[project]]
name = "Vortex"
desc = "Nouns DAO anonymous voting ⌐◨-◨. Winner of Nouns [Private voting research sprint](https://prop.house/nouns/private-voting-research-sprint)."
links = [
  { name = "GitHub", url = "https://github.com/mizu-dao/vortex" },
  { name = "Docs", url = "https://mizu-dao.github.io/vortex/" },
]

[[project]]
name = "VoAn"
desc = "ANonymous VOting platform on NEAR Protocol."
links = [
  { name = "GitHub", url = "https://github.com/curryrasul/voan" },
  { name = "Docs", url = "https://curryrasul.github.io/voan" },
  { name = "App", url = "https://voan.site" },
]

[[project]]
name = "pmtree"
desc = "Persistent, sparse and generic Merkle tree in Rust. Inspired by [monotree](https://github.com/thyeem/monotree)."
links = [
  { name = "GitHub", url = "https://github.com/Rate-Limiting-Nullifier/pmtree" },
  { name = "Crates.io", url = "https://crates.io/crates/pmtree" },
]